---
title: "Citations personnelles en gras"
output:
  html_document:
    df_print: paged
    pandoc_args: "--lua-filter=fr-nbsp.lua"
  pdf_document:
    keep_tex: true
bibliography: references.bib
---

Ce test utilise deux citations **[@Abe2001]**+[@Acs1991; @Adelman1969] séparée par un `+`.
Attention: le mode visuel de R Studio modifie le code: c'est un problème, il ne faut surtout pas passer en mode visuel!

Autres cas:

- une citation grasse à la fin: [@Abe2001]+**[@Acs1991]**.
- une citation grasse au milieu : [@Abe2001]+**[@Acs1991]**+[@Adelman1969].

Le script `post-treatment.R` permet de remplacer les parenthèses en trop par un point-virgule.
Il laisse les parenthèses de début ou de fin en gras, ce qui est imparfait, mais il n'y a pas de moyen simple de reconnaître les parenthèses de fin de citation.

Pour la version PDF, il faut conserver le fichier TeX (`keep_tex: true`), exécuter le script de post-traitement, puis ouvrir le fichier TeX final et enfin le compiler.

Remarque : le filtre LUA formate correctement la ponctuation en français dans le fichier HTML.

`r if (!knitr:::is_latex_output()) '# References {-}'`
