on:
  push:
   branches:
     - master

name: rmarkdown

jobs:
  render:
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Install dependencies
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
        run: |
          options(pkgType = "binary")
          options(install.packages.check.source = "no")
          install.packages(c("distill", "downlit", "memoiR", "rmdformats", "tinytex"))
          tinytex::install_tinytex(bundle = "TinyTeX")
        shell: Rscript {0}
      - name: Render Rmarkdown files
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
        run: |
          # knit
          lapply(list.files(pattern="*.Rmd"), function(file) rmarkdown::render(file, "all"))
          # post-treatment
          source("post-treatment.R")
          # Move outputs to docs/
          if (!dir.exists("docs")) dir.create("docs")
          files_to_move <- list.files(pattern = "*_final.*")
          file.rename(from = files_to_move, to = paste("docs/", files_to_move, sep = ""))
          file.copy(from = "README.md", to = "docs/README.md", overwrite = TRUE)
        shell: Rscript {0}
      - name: GH Pages Theme
        run: |
          echo 'theme: jekyll-theme-slate' > docs/_config.yml
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ghpages
          path: docs
  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: render
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ghpages
          path: docs
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          email: ${{ secrets.EMAIL }}
          build_dir: docs
          jekyll: yes
